import 'package:aboelazayem/new_screens/new_quran/ayat_from_swar_screen.dart';
import 'package:flutter/material.dart';

import '../quran_api.dart';

class AyatFromJuza30 extends StatefulWidget {
  @override
  _AyatFromJuza30State createState() => _AyatFromJuza30State();
}

class _AyatFromJuza30State extends State<AyatFromJuza30> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: PageView(
      scrollDirection: Axis.horizontal,
      children: [
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 40,
            swraId: 78,
            nextSwraName: "",
            swraName: "النبأ",
            place: "مكية",
            ayaCount: "40 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 46,
            swraId: 79,
            nextSwraName: "",
            swraName: "النازعات",
            place: "مكية",
            ayaCount: "46 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 42,
            swraId: 80,
            nextSwraName: "",
            swraName: "عبس",
            place: "مكية",
            ayaCount: "42 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 29,
            swraId: 81,
            nextSwraName: "",
            swraName: "التكوير",
            place: "مكية",
            ayaCount: "29 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 19,
            swraId: 82,
            nextSwraName: "",
            swraName: "الانفطار",
            place: "مكية",
            ayaCount: "19 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 36,
            swraId: 83,
            nextSwraName: "",
            swraName: "المطففين",
            place: "مكية",
            ayaCount: "36 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 25,
            swraId: 84,
            nextSwraName: "",
            swraName: "الانشقاق",
            place: "مكية",
            ayaCount: "25 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 22,
            swraId: 85,
            nextSwraName: "",
            swraName: "البروج",
            place: "مكية",
            ayaCount: "22 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 17,
            swraId: 86,
            nextSwraName: "",
            swraName: "الطارق",
            place: "مكية",
            ayaCount: "17 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 19,
            swraId: 87,
            nextSwraName: "",
            swraName: "الأعلى",
            place: "مكية",
            ayaCount: "19 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 26,
            swraId: 88,
            nextSwraName: "",
            swraName: "الغاشية",
            place: "مكية",
            ayaCount: "26 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 30,
            swraId: 89,
            nextSwraName: "",
            swraName: "الفجر",
            place: "مكية",
            ayaCount: "30 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 20,
            swraId: 90,
            nextSwraName: "",
            swraName: "البلد",
            place: "مكية",
            ayaCount: "20 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 15,
            swraId: 91,
            nextSwraName: "",
            swraName: "الشمس",
            place: "مكية",
            ayaCount: "15 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 21,
            swraId: 92,
            nextSwraName: "",
            swraName: "الليل",
            place: "مكية",
            ayaCount: "21 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 11,
            swraId: 93,
            nextSwraName: "",
            swraName: "الضحى",
            place: "مكية",
            ayaCount: "11 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 8,
            swraId: 94,
            nextSwraName: "",
            swraName: "الشرح",
            place: "مكية",
            ayaCount: "8 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 8,
            swraId: 95,
            nextSwraName: "",
            swraName: "التين",
            place: "مكية",
            ayaCount: "8 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 19,
            swraId: 96,
            nextSwraName: "",
            swraName: "العلق",
            place: "مكية",
            ayaCount: "19 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 5,
            swraId: 97,
            nextSwraName: "",
            swraName: "القدر",
            place: "مكية",
            ayaCount: "5 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 8,
            swraId: 98,
            nextSwraName: "",
            swraName: "البينة",
            place: "مدنية",
            ayaCount: "8 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 8,
            swraId: 99,
            nextSwraName: "",
            swraName: "الزلزلة",
            place: "مدنية",
            ayaCount: "8 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 11,
            swraId: 100,
            nextSwraName: "",
            swraName: "العاديات",
            place: "مكية",
            ayaCount: "11 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 11,
            swraId: 101,
            nextSwraName: "",
            swraName: "القارعة",
            place: "مكية",
            ayaCount: "11 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 8,
            swraId: 102,
            nextSwraName: "",
            swraName: "التكاثر",
            place: "مكية",
            ayaCount: "8 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 3,
            swraId: 103,
            nextSwraName: "",
            swraName: "العصر",
            place: "مكية",
            ayaCount: "3 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 9,
            swraId: 104,
            nextSwraName: "",
            swraName: "الهمزة",
            place: "مكية",
            ayaCount: "9 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 5,
            swraId: 105,
            nextSwraName: "",
            swraName: "الفيل",
            place: "مكية",
            ayaCount: "5 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 4,
            swraId: 106,
            nextSwraName: "",
            swraName: "قريش",
            place: "مكية",
            ayaCount: "4 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 7,
            swraId: 107,
            nextSwraName: "",
            swraName: "الماعون",
            place: "مكية",
            ayaCount: "7 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 3,
            swraId: 108,
            nextSwraName: "",
            swraName: "الكوثر",
            place: "مكية",
            ayaCount: "3 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 6,
            swraId: 109,
            nextSwraName: "",
            swraName: "الكافرون",
            place: "مكية",
            ayaCount: "6 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 3,
            swraId: 110,
            nextSwraName: "",
            swraName: "النصر",
            place: "مدنية",
            ayaCount: "3 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 5,
            swraId: 111,
            nextSwraName: "",
            swraName: "المسد",
            place: "مكية",
            ayaCount: "5 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 4,
            swraId: 112,
            nextSwraName: "",
            swraName: "الإخلاص",
            place: "مكية",
            ayaCount: "4 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 5,
            swraId: 113,
            nextSwraName: "",
            swraName: "الفلق",
            place: "مكية",
            ayaCount: "5 أية ",
            nextPlace: "",
            nextAyaCount: ""),
        AyatFromSwarScreen(
            juzaCat: true,
            juzaAyaCount: 6,
            swraId: 114,
            nextSwraName: "",
            swraName: "الناس",
            place: "مكية",
            ayaCount: "6 أية ",
            nextPlace: "",
            nextAyaCount: ""),
      ],
    ));
  }
}
